### ISSUE TITLE
Content–similarity loss

### ISSUE THREAD

**Issue by YiruS** [vaibhavnaagar/pixelDA_GAN#1]
Hi,

Thanks for sharing the codebase for PixelDA!  Just one question, it seems that content–similarity loss is not utilized in this code? Or do I missing something?

Thanks!

**Comment by vaibhavnaagar** [comment]
Hello,
Yes, you are right, content-similarity loss is not utilized. You can add
this loss in the generator loss. The paper has used masked PMSE for
transfer similarity loss.
You can find the logic of masked PMSE in tensorflow:
https://github.com/tensorflow/models/blob/master/research/domain_adaptation/pixel_domain_adaptation/pixelda_losses.py#L222

Thanks,
Vaibhav
